package com.example.admin.infrastructure.persistence;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.time.Instant;

@Entity
@Table(name = "admin_actions")
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class AdminActionJpaEntity {

    // Internal BIGINT surrogate PK (TASK-BE-028b1). Not surfaced in API responses.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;

    // Preserved UUID from the pre-028b1 schema. Continues to be the `auditId`
    // string returned in API responses for backward compatibility; the application
    // layer correlates IN_PROGRESS → terminal outcome by this value.
    @Column(name = "legacy_audit_id", length = 36, unique = true)
    private String legacyAuditId;

    @Column(name = "action_code", length = 50, nullable = false)
    private String actionCode;

    @Column(name = "actor_id", length = 100, nullable = false)
    private String actorId;

    @Column(name = "actor_role", length = 30, nullable = false)
    private String actorRole;

    // BIGINT FK → admin_operators.id (internal PK). Nullable in this increment
    // because the UUID→BIGINT resolution path lives in TASK-BE-028b2.
    @Column(name = "operator_id")
    private Long operatorId;

    // The permission key evaluated for this action (or "<missing>").
    @Column(name = "permission_used", length = 80)
    private String permissionUsed;

    @Column(name = "target_type", length = 30, nullable = false)
    private String targetType;

    @Column(name = "target_id", length = 100, nullable = false)
    private String targetId;

    @Column(name = "reason", length = 1000, nullable = false)
    private String reason;

    @Column(name = "ticket_id", length = 100)
    private String ticketId;

    @Column(name = "idempotency_key", length = 100, nullable = false)
    private String idempotencyKey;

    @Column(name = "outcome", length = 20, nullable = false)
    private String outcome;

    @Column(name = "downstream_detail", columnDefinition = "TEXT")
    private String downstreamDetail;

    @Column(name = "started_at", nullable = false)
    private Instant startedAt;

    @Column(name = "completed_at")
    private Instant completedAt;

    /**
     * Legacy 13-arg factory retained for call sites that do not carry the
     * operator BIGINT FK yet (UUID→BIGINT mapping lands in TASK-BE-028b2).
     * The external UUID is stored in {@code legacyAuditId}; the numeric PK is
     * generated by the database.
     */
    public static AdminActionJpaEntity create(String legacyAuditId,
                                              String actionCode,
                                              String actorId,
                                              String actorRole,
                                              String targetType,
                                              String targetId,
                                              String reason,
                                              String ticketId,
                                              String idempotencyKey,
                                              String outcome,
                                              String downstreamDetail,
                                              Instant startedAt,
                                              Instant completedAt) {
        return create(legacyAuditId, actionCode, actorId, actorRole, null, null,
                targetType, targetId, reason, ticketId, idempotencyKey,
                outcome, downstreamDetail, startedAt, completedAt);
    }

    public static AdminActionJpaEntity create(String legacyAuditId,
                                              String actionCode,
                                              String actorId,
                                              String actorRole,
                                              Long operatorId,
                                              String permissionUsed,
                                              String targetType,
                                              String targetId,
                                              String reason,
                                              String ticketId,
                                              String idempotencyKey,
                                              String outcome,
                                              String downstreamDetail,
                                              Instant startedAt,
                                              Instant completedAt) {
        AdminActionJpaEntity e = new AdminActionJpaEntity();
        e.legacyAuditId = legacyAuditId;
        e.actionCode = actionCode;
        e.actorId = actorId;
        e.actorRole = actorRole;
        e.operatorId = operatorId;
        e.permissionUsed = permissionUsed;
        e.targetType = targetType;
        e.targetId = targetId;
        e.reason = reason;
        e.ticketId = ticketId;
        e.idempotencyKey = idempotencyKey;
        e.outcome = outcome;
        e.downstreamDetail = downstreamDetail;
        e.startedAt = startedAt;
        e.completedAt = completedAt;
        return e;
    }

    /**
     * Finalizes an IN_PROGRESS row. The DB trigger
     * {@code trg_admin_actions_finalize_only} enforces that only
     * {@code outcome}, {@code downstream_detail}, and {@code completed_at} may change.
     */
    public void finalizeOutcome(String outcome, String downstreamDetail, Instant completedAt) {
        this.outcome = outcome;
        this.downstreamDetail = downstreamDetail;
        this.completedAt = completedAt;
    }
}
